security:
    role_hierarchy:
        ROLE_EDITOR : ROLE_USER
        ROLE_ADMIN : ROLE_EDITOR
        ROLE_SUPER_ADMIN : ROLE_EDITOR
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12
    providers:
        in_memory:
            memory:
                users:
                    user:
                        password: '$2y$12$IPRzmXOEYdCF2OMMXdPVcOHA1fFm8sW/YSTftWXULXWVie3AJd2.i'
                        roles: 'ROLE_USER'
                    kadir:
                        password: '$2y$12$qc46LxjG8XPd2lIxpxDVAO4GF6sjnJAirQ4fa4.PiAA.WpqaYm7ha'
                        #şifrelenmemiş haliyle giriş yapmıyor
                        roles: 'ROLE_EDITOR'
                    admin:
                        password: '$2y$12$MsxN5pLD3i9SX9xl1bZOeeCk1ZbDfA/WHuObzI04RAeSNX/EaXAFO'
                        #admin123'ün sifrelenmis hali: $2y$12$MsxN5pLD3i9SX9xl1bZOeeCk1ZbDfA/WHuObzI04RAeSNX/EaXAFO
                        roles: 'ROLE_ADMIN'
                    superadmin:
                        password: '$2y$12$rfRvHaa.fQk8wQr9aru8Se4HgoGdB7Yhtl8WVwTyWyrI3BZsmZj3C'
                        roles: 'ROLE_SUPER_ADMIN'
                        #şifrelenmemiş haliyle giriş yapmıyor
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            form_login:
                login_path: login
                check_path: login
            logout:
                path: /logout
                target: /
                #default_target_path: admin
            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/profile, roles: ROLE_USER }
